"""Gameplay rank tables and balance constants."""

RANK_VISITS = {
    "18k": 2,
    "17k": 3,
    "16k": 5,
    "15k": 8,
    "14k": 12,
    "13k": 18,
    "12k": 28,
    "11k": 40,
    "10k": 60,
    "9k": 90,
    "8k": 130,
    "7k": 180,
    "6k": 260,
    "5k": 380,
    "4k": 550,
    "3k": 800,
    "2k": 1100,
    "1k": 1500,
    "a1d": 2200,
    "a2d": 3500,
    "a3d": 5500,
    "a4d": 9000,
    "a5d": 12000,
    "a6d": 15000,
    "a7d": 18000,
    "a8d": 20000,
    "a9d": 22000,
    "p1d": 24000,
    "p2d": 26000,
    "p3d": 28000,
    "p4d": 30000,
    "p5d": 32000,
    "p6d": 34000,
    "p7d": 36000,
    "p8d": 38000,
    "p9d": 0,
}

RANK_LABELS = {
    "18k": "18级",
    "17k": "17级",
    "16k": "16级",
    "15k": "15级",
    "14k": "14级",
    "13k": "13级",
    "12k": "12级",
    "11k": "11级",
    "10k": "10级",
    "9k": "9级",
    "8k": "8级",
    "7k": "7级",
    "6k": "6级",
    "5k": "5级",
    "4k": "4级",
    "3k": "3级",
    "2k": "2级",
    "1k": "1级",
    "a1d": "业余1段",
    "a2d": "业余2段",
    "a3d": "业余3段",
    "a4d": "业余4段",
    "a5d": "业余5段",
    "a6d": "业余6段",
    "a7d": "业余7段",
    "a8d": "业余8段",
    "a9d": "业余9段",
    "p1d": "职业一段",
    "p2d": "职业二段",
    "p3d": "职业三段",
    "p4d": "职业四段",
    "p5d": "职业五段",
    "p6d": "职业六段",
    "p7d": "职业七段",
    "p8d": "职业八段",
    "p9d": "职业九段",
}

MAX_GAME_VISITS = 20000
ROGUE_MAX_VISITS = 800
ULTIMATE_MAX_VISITS = 400
CPU_MAX_VISITS = 250

ROGUE_DICE_PASS_CHANCE = 0.08
ROGUE_SLIP_CHANCE = 0.10
ROGUE_MIRROR_CHANCE = 0.10
ROGUE_NERF_FACTOR = 0.05
ROGUE_NERF_BACKUP_CHANCE = 0.60
ROGUE_NERF_BACKUP_AI_MOVES = 12
ROGUE_EROSION_SHIFT = 4.0
ROGUE_TENGEN_AI_MOVES = 5
ROGUE_FOG_MASK_RADIUS = 1
ROGUE_FOG_AI_MOVES = 11
ROGUE_FOG_POST_MASK_POINTS = 2
ROGUE_BLACKHOLE_AI_MOVES = 6
ROGUE_GOLDEN_CORNER_AI_MOVES = 10
ROGUE_GOLDEN_CORNER_SPAN = 4
ROGUE_GRAVITY_AI_MOVES = 7
ROGUE_LOWLINE_AI_MOVES = 8
ROGUE_SHADOW_AI_MOVE_INDEXES = {1, 2, 3}
ROGUE_SHADOW_CHANCE = 0.70
ROGUE_SUBOPTIMAL_AI_MOVES = 8
ROGUE_TIME_PRESS_MAX_TIME = 0.10
ROGUE_TIME_PRESS_MAX_VISITS = 20
ROGUE_TIME_PRESS_BACKUP_CHANCE = 0.60
ROGUE_TIME_PRESS_BACKUP_AI_MOVES = 12
ROGUE_FOOLISH_FILL_COUNT = 2
ULTIMATE_FOOLISH_FILL_COUNT = 20
ULTIMATE_FOOLISH_CHAIN_DELAY = 1.0
ROGUE_HANDICAP_REQUIRED_PASSES = 1
ROGUE_HANDICAP_BONUS_INTERVAL = 8
ROGUE_HANDICAP_MAX_BONUSES = 3
ROGUE_JOSEKI_TARGET_COUNT = 7
ROGUE_JOSEKI_REQUIRED_HITS = 6
ROGUE_GODHAND_FILL_COUNT = 2
ROGUE_GODHAND_RADIUS = 1
ROGUE_CORNER_HELPER_TRIGGER_STONES = 4
ROGUE_CORNER_HELPER_STONES = 1
ROGUE_SANRENSEI_REQUIRED_STARS = 2
ROGUE_SANRENSEI_OPENING_MOVES = 2
ROGUE_SANRENSEI_BONUS_STONES = 1
ROGUE_SANRENSEI_SUPPORT_STONES = 1
ROGUE_NO_REGRET_CHANCE = 0.10
ROGUE_QUICKTHINK_FIRST_SECONDS = 4
ROGUE_QUICKTHINK_SECOND_SECONDS = 2
ROGUE_SANSAN_TRAP_STONES = 8
ROGUE_SEAL_POINT_COUNT = 4
ROGUE_FIVE_IN_ROW_SUPPORT_STONES = 4

ULTIMATE_CHAIN_EXTRA_TURN_CHANCE = 0.65
ULTIMATE_WILDGROW_MAX_GROWTH = 4
ULTIMATE_METEOR_DESTROY_COUNT = 5
ULTIMATE_QUANTUM_PLACE_COUNT = 5
ULTIMATE_TIMEWARP_TRIGGER_CHANCE = 0.85
ULTIMATE_TERRITORY_RADIUS = 4
ULTIMATE_JOSEKI_TARGET_COUNT = 7
ULTIMATE_JOSEKI_REQUIRED_HITS = 3
ULTIMATE_JOSEKI_BONUS_STONES = 50
ULTIMATE_GODHAND_FILL_COUNT = 50
ULTIMATE_QUICKTHINK_SECONDS = 5
ULTIMATE_WALL_TRIGGER_CHANCE = 0.60
ROGUE_LAST_STAND_THRESHOLD = 0.26
ULTIMATE_LAST_STAND_THRESHOLD = 0.30
ROGUE_LAST_STAND_CLEAR_COUNT = 1
ROGUE_LAST_STAND_SPAWN_COUNT = 1
ULTIMATE_LAST_STAND_CLEAR_COUNT = 30
ULTIMATE_LAST_STAND_SPAWN_COUNT = 30
ULTIMATE_FIVE_IN_ROW_CLEAR_COUNT = 30
ULTIMATE_FIVE_IN_ROW_SPAWN_COUNT = 30

MAX_MOVE_TIME = 12.0
OPENING_MOVE_THRESHOLD = 50
OPENING_MAX_VISITS = 500
AI_STYLE_OPTIONS = {"balanced", "territory", "influence", "attack", "defense"}

ROGUE_CAPTURE_FOUL_BASE = 1.00
ROGUE_CAPTURE_FOUL_STEP = 0.00
ROGUE_CAPTURE_FOUL_THRESHOLD = 4
ROGUE_CAPTURE_FOUL_KOMI_PENALTY = 4.0
ULTIMATE_CAPTURE_FOUL_THRESHOLD = 5
ULTIMATE_CAPTURE_FOUL_SCORE_PENALTY = 50.0
ROGUE_COACH_BASE_TURNS = 30
ROGUE_COACH_BONUS_TURNS = 10
ROGUE_COACH_BONUS_THRESHOLD = 0.50
ROGUE_COACH_VISITS = 20000

CHALLENGE_STAGE_BIAS_WEIGHT = 2.6
CHALLENGE_SET_MIN_COUNT = 2
CHALLENGE_DERIVATIVE_BONUS_CHANCE = 0.50
CHALLENGE_TRAP_EXTRA_TURN_CHANCE = 1.0
CHALLENGE_ZONE_EXPAND_RADIUS = 1
CHALLENGE_RESTRICTION_DECAY_CHANCE = 0.05
CHALLENGE_ACTIVE_USE_BONUS = 1
